name: Upgrade system

runs:
  using: "composite"

  steps:
    - name: Refresh package databases
      shell: bash
      run: pacman --sync --noconfirm --refresh

    - name: Upgrade system
      shell: bash
      run: pacman --sync --noconfirm --sysupgrade

    - name: Install required packages
      shell: bash
      run: pacman --sync --noconfirm --needed pacman-contrib

    - name: Remove outdated packages from cache
      shell: bash
      run: paccache --keep 1 --remove
