name: Create users

runs:
  using: "composite"

  steps:
    - name: Create non-root user
      shell: bash
      run: useradd user --groups wheel --create-home

    - name: Configure sudoers
      shell: bash
      run: |-
        echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
