import yaml
import pathlib

#####

class Config:
    def __init__(self, path):
        with open(path, "r") as file:
            self._config = yaml.safe_load(file)

        #####

        if "input" in self._config:
            self._input = self._config["input"]
        else:
            self._input = "packages"

        #####

        if "output" in self._config:
            self._output = self._config["output"]
        else:
            self._output = ".github/workflows/autogenerated-builder.yml"

        #####

        if "runs-on" in self._config:
            self._runs_on = self._config["runs-on"]
        else:
            self._runs_on = "ubuntu-latest"

        #####

        if "timeout" in self._config:
            self._timeout = self._config["timeout"]
        else:
            self._timeout = 360

        #####

        if "overrides" in self._config:
            self._overrides = self._config["overrides"]
        else:
            self._overrides = {}

    ##########

    def get_input(self):
        return pathlib.Path(self._input)

    #####

    def get_output(self):
        return pathlib.Path(self._output)

    #####

    def is_build(self, name):
        if name in self._overrides:
            if "build" in self._overrides[name]:
                return self._overrides[name]["build"]

        #####

        return True

    #####

    def runs_on(self, name):
        if name in self._overrides:
            if "runs-on" in self._overrides[name]:
                return self._overrides[name]["runs-on"]

        #####

        return self._runs_on

    #####

    def timeout(self, name):
        if name in self._overrides:
            if "timeout" in self._overrides[name]:
                return self._overrides[name]["timeout"]

        #####

        return self._timeout
