def action_template(jobs):
    return {
        "name": "Builder (Autogenerated)",
        "run-name": "Build package tree",

        "on": [
            "workflow_dispatch"
        ],

        "jobs": jobs
    }
